site_name: PyTau
site_description: "Simple python package to perform streamlined batch inference on changepoint models"

theme:
  name: "mkdocs"
  palette:
    primary: "blue"
    accent: "grey"
  features:
      - toc.integrate
      - navigation.sections

plugins:
  - search
  - mkdocstrings

nav:
  - "Home": index.md
  - "User Guide":
    - "Available Models": models.md
    - "Inference Methods": inference.md
    - "Data Formats": data_formats.md
    - "Pipeline Architecture": pipeline.md
  - "PyMC Concepts": pymc_concepts.md
  - "API Reference": api.md
